#
# Copyright (c) 2025 Graphcore Ltd. All rights reserved.
#
from pathlib import Path
import json

import torch
import pytest
import tomli_w
import tensor_tracker
from torch.distributed.checkpoint.state_dict import get_model_state_dict

from low_bits_training.utils import job_config_to_config_dict
from low_bits_training import checkpoints

from low_bits_training.config import JobConfig

TEST_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = TEST_ROOT.parent

TEST_ASSET_DIRECTORY = TEST_ROOT / "assets/"


def config_to_toml(config):
    flattened_dict = job_config_to_config_dict(config)

    def remove_nones(d):
        if isinstance(d, dict):
            return {k: remove_nones(v) for k, v in d.items() if v is not None}
        return d

    flattened_dict = remove_nones(flattened_dict)

    tomli_string = tomli_w.dumps(flattened_dict)
    return tomli_string


def test_checkpoint(config_and_checkpoint: tuple[JobConfig, Path], tmp_path):
    config, checkpoint = config_and_checkpoint

    config_file = tmp_path / "config.toml"
    config_file.write_text(config_to_toml(config))

    loader = checkpoints.REGISTERED_CHECKPOINT_CONVERSIONS[config.model.name]

    with pytest.raises(ValueError):
        loader._check_assigned(["tt_config_class"])

    transformers_model = loader.load_transformers_model(config, str(checkpoint))
    transformers_model.save_pretrained(tmp_path)

    loader.load_tt_model_and_tokenizer(config_file, str(checkpoint))
    transformers_model = loader.load_transformers_model(str(config_file), str(checkpoint))

    checkpoints.load_tt_tokenizer(config)


def test_config_loading(config_and_checkpoint: tuple[JobConfig, Path], tmp_path: Path):
    config, _ = config_and_checkpoint
    config_dict = job_config_to_config_dict(config)

    toml_file = tmp_path / "config.toml"
    toml_file.write_text(config_to_toml(config))

    json_file = tmp_path / "config.json"
    json_file.write_text(json.dumps(config_dict))

    toml_config = checkpoints.load_config(toml_file, allow_upgrade=True)
    json_config = checkpoints.load_config(json_file, allow_upgrade=True)

    toml_dict = job_config_to_config_dict(toml_config)
    json_dict = job_config_to_config_dict(json_config)
    for d in [toml_dict, config_dict, json_dict]:
        d["job"].pop("config_file")
        d["job"].pop("dump_folder")
    assert toml_dict == config_dict
    assert json_dict == config_dict


def _compare_tracker_dicts_layer_by_layer(
    tt_tracker_dict: dict[str, tensor_tracker.Stash],
    transformers_tracker_dict: dict[str, tensor_tracker.Stash],
    allow_missing_keys: list[str] = [],
) -> tuple[
    list[tuple[str, AssertionError]], list[tuple[str, Exception]], list[str], list[str]
]:
    """
    Compares two dictionaries of tensor_tracker.Stash objects.

    These can be generated by the tensor_tracker.track context manager.

    Returns the mismatches, comparison errors and missing keys in the
    torchtitan and transformers tracker dictionaries

    """
    missing_keys_in_tt = []
    for key in transformers_tracker_dict.keys():
        if key not in tt_tracker_dict:
            missing_keys_in_tt.append(key)
    print(f"Missing keys in tt: {missing_keys_in_tt}")
    missing_keys_in_transformers = []
    for key in tt_tracker_dict.keys():
        if key not in transformers_tracker_dict and key not in allow_missing_keys:
            missing_keys_in_transformers.append(key)
    print(f"Missing keys in transformers: {missing_keys_in_transformers}")
    assert not missing_keys_in_transformers
    mismatches = []
    comparison_errors = []
    for key in tt_tracker_dict.keys():
        if key in allow_missing_keys:
            continue
        # Q and K are interleaved in torchtitan and concatenated together in transformers
        # this means we expect them to be different
        tt_value = tt_tracker_dict[key].value
        transformers_value = transformers_tracker_dict[key].value
        try:
            torch.testing.assert_close(tt_value, transformers_value, rtol=0, atol=0)
        except AssertionError as e:
            mismatches.append((key, e))
            print(f"Mismatch for {key}: {e}")
        except Exception as e:
            print(f"Error for {key}: {e}")
            comparison_errors.append((key, e))
    return mismatches, comparison_errors, missing_keys_in_tt, missing_keys_in_transformers


@pytest.mark.parametrize("model_dtype", [None, torch.bfloat16])
def test_unit_test_model_equivalence(
    no_distribution, config_and_checkpoint, model_dtype: torch.dtype
):
    """Checks that the transformers version and torchtitan version of the model have
    the same output"""
    config, checkpoint_path = config_and_checkpoint
    if model_dtype:
        config.model.converters.append(str(model_dtype).replace("torch.", ""))
    tt_model, _ = checkpoints.load_tt_model_and_tokenizer(config)

    state_dict = {"model": get_model_state_dict(tt_model)}
    print(str(list(state_dict["model"].keys())))
    checkpoints.dcp_load_helper(state_dict, checkpoint_id=checkpoint_path)

    transformers_model = checkpoints.REGISTERED_CHECKPOINT_CONVERSIONS[
        "llama3_gc"
    ].load_transformers_model(config, str(checkpoint_path))
    if model_dtype:
        transformers_model.to(dtype=model_dtype)

    # This test can be brittle where one or two of the tokens will have and error of the order
    # of 1e-7
    num_tokens = 16
    allowed_diffs = 2
    input_ids = torch.tensor(range(num_tokens), dtype=torch.long).reshape(1, num_tokens)
    with tensor_tracker.track(tt_model) as tt_tracker:
        tt_out = tt_model(input_ids)
    with tensor_tracker.track(transformers_model) as transformers_tracker:
        transformers_out = transformers_model(input_ids)

    token_diffs = (tt_out - transformers_out.logits).abs().sum(axis=2).flatten().tolist()
    # If there are mismatches we do a layer by layer comparison
    mismatches = []
    # if there are any token diffs we do additional checks (these will not trigger errors)
    if any(token_diffs):
        # We remap the keys to compare the torchtitan and transformers state dicts
        additional_remaps = {
            "model.": "",
            "model": "",
            "self_attn": "attention",
            "mlp": "feed_forward",
        }
        tt_tracker_dict = {
            i.name.replace("._checkpoint_wrapped_module", ""): i for i in tt_tracker
        }
        transformers_tracker_dict = checkpoints.rename_state_dict_entry(
            additional_remaps,
            checkpoints.rename_state_dict_entry(
                checkpoints.Llama3StateDictConverter.remap_keys,
                {i.name: i for i in transformers_tracker},
            ),
        )
        mismatches, *_ = _compare_tracker_dicts_layer_by_layer(
            tt_tracker_dict,
            transformers_tracker_dict,
            allow_missing_keys=["layers.0.attention.sdpa", "layers.1.attention.sdpa"],
        )
    # Find the tokens that have a mismatch
    mismatched_tokens, *_ = torch.where(torch.tensor(token_diffs) > 0)
    assert len(mismatched_tokens) <= allowed_diffs, (
        f"Some tokens outputs do not match, tokens with ID "
        f"{mismatched_tokens} have a mismatch of {torch.tensor(token_diffs)[mismatched_tokens]},"
        f" tensors mismatching: {[n for n, _ in mismatches]}"
    )
    # Stricter test on the full output - disabled as it can be brittle
    # torch.testing.assert_close(tt_out, transformers_out.logits, rtol=0, atol=0)


def compare_state_dicts(model_dict, ref_state_dict, force_dtype=None, show_success=False):
    """Compares all the tensors of two model state_dicts"""
    mismatches = []
    num_pass = 0
    num_fail = 0
    for name, tensor in model_dict.items():
        ref_tensor = ref_state_dict[name]
        try:
            if force_dtype is None:
                torch.testing.assert_close(tensor, ref_tensor, rtol=0, atol=0)
            else:
                torch.testing.assert_close(
                    tensor.to(dtype=force_dtype),
                    ref_tensor.to(dtype=force_dtype),
                    rtol=0,
                    atol=0,
                )
            num_pass += 1
            if show_success:
                print(f"Success for {name}")
        except AssertionError as error:
            mismatches.append((name, str(error), error))
            num_fail += 1
            print(f"Fail for {name} - {num_fail} / {num_fail + num_pass}")
            print("Tensor   : ", tensor.mean(), tensor.max(), tensor.abs().mean())
            print(
                "Reference: ",
                ref_tensor.mean(),
                ref_tensor.max(),
                ref_tensor.abs().mean(),
            )
    print(f"There were {len(mismatches)} errors")
    return mismatches
