GPU := B200

SRC := mxfp4_cce_v2.cu
OUT := _C_mx_cce_v2$(shell python3 -c "import sysconfig; print(sysconfig.get_config_var('EXT_SUFFIX'))")
CMD := echo "built"
NVCCFLAGS := -DTORCH_COMPILE
CONFIG := pytorch

include ../../common.mk

NVCCFLAGS += -DTORCH_EXTENSION_NAME=_C_mx_cce_v2
