#
# Copyright (c) 2025 Graphcore Ltd. All rights reserved.
#
import pytest
import subprocess
import sys
import time
import threading
import signal
from unittest.mock import MagicMock

from low_bits_training.utils import run_process_with_realtime_output


@pytest.fixture
def create_script(tmp_path):
    """Fixture to create a temporary Python script."""
    scripts = []

    def _create_script(content, filename="test_script.py"):
        script_path = tmp_path / filename
        script_path.write_text(content)
        scripts.append(script_path)
        return str(script_path)

    return _create_script


class TestRunProcessWithRealtimeOutput:
    """Tests for the run_process_with_realtime_output function.

    Tests generated by Claude to cover the improved clean-up logic of the function.
    """

    def test_bytes_output_handling(self, create_script, capfd):
        """Test that the function correctly handles bytes output from subprocess."""
        script_content = """
import sys
# Output exactly 1000 characters to stdout
data = "A" * 1000
sys.stdout.write(data)
sys.stdout.flush()
# Output 500 characters to stderr
stderr_data = "B" * 500
sys.stderr.write(stderr_data)
sys.stderr.flush()
sys.exit(0)
    """
        script_path = create_script(script_content)

        process = subprocess.Popen(
            [sys.executable, script_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=False,  # Use bytes mode to match the fixed function
        )

        return_code = run_process_with_realtime_output(process)
        captured = capfd.readouterr()

        assert return_code == 0
        # Verify all data was captured correctly
        assert len(captured.out) == 1000
        assert all(c == "A" for c in captured.out)
        assert len(captured.err) == 500
        assert all(c == "B" for c in captured.err)

    def test_large_output_streaming(self, create_script, capfd):
        """Test that large output is handled correctly with streaming."""
        script_content = """
import sys
import time
# Generate large output in chunks to test streaming
for i in range(100):
    sys.stdout.write(f"Line {i:03d}: {'X' * 50}\\n")
    sys.stdout.flush()
    if i % 10 == 0:
        sys.stderr.write(f"Progress: {i}%\\n")
        sys.stderr.flush()
    # Small delay to make streaming more realistic
    time.sleep(0.001)
sys.exit(0)
    """
        script_path = create_script(script_content)

        process = subprocess.Popen(
            [sys.executable, script_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=False,
        )

        return_code = run_process_with_realtime_output(process)
        captured = capfd.readouterr()

        assert return_code == 0
        # Verify we got all 100 lines of output
        stdout_lines = captured.out.strip().split("\n")
        assert len(stdout_lines) == 100
        assert "Line 000:" in stdout_lines[0]
        assert "Line 099:" in stdout_lines[99]

        # Verify progress messages in stderr
        assert "Progress: 0%" in captured.err
        assert "Progress: 90%" in captured.err

    def test_thread_cleanup_warning_scenario(self, create_script, capfd):
        """Test cleanup warnings appear when threads take time to finish."""
        script_content = """
import sys
import time
import signal

# Create a script that outputs data and then exits quickly
# This might create a scenario where threads need cleanup time
for i in range(10000):
    sys.stdout.write(f"Fast output {i}\\n")
    sys.stderr.write(f"Fast error {i}\\n")

# Flush all output
sys.stdout.flush()
sys.stderr.flush()

# Exit immediately
sys.exit(0)
    """
        script_path = create_script(script_content)

        process = subprocess.Popen(
            [sys.executable, script_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=False,
            bufsize=0,  # Unbuffered to make output immediate
        )

        # Use unbuffered mode to make output immediate
        return_code = run_process_with_realtime_output(process)
        captured = capfd.readouterr()

        assert return_code == 0
        # The main test is that the function completes without raising RuntimeError
        # If cleanup warnings appear, they'll be in stderr, but this is timing-dependent

        # Verify we got the expected output
        assert "Fast output 0" in captured.out
        assert "Fast output 9999" in captured.out
        assert "Fast error 0" in captured.err
        assert "Fast error 9999" in captured.err

    def test_process_with_mixed_text_binary_modes(self, create_script, capfd):
        """Test that the function works correctly with text=False subprocess mode."""
        script_content = """
import sys
# Test with unicode and special characters
sys.stdout.write("Hello 🌍 World\\n")
sys.stderr.write("Error with émojis 🚨\\n")
# Test with bytes-like output
sys.stdout.buffer.write(b"Binary data: \\x00\\x01\\x02\\n")
sys.stderr.buffer.write(b"Binary error: \\xff\\xfe\\n")
sys.exit(0)
    """
        script_path = create_script(script_content)

        process = subprocess.Popen(
            [sys.executable, script_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=False,  # This is key - binary mode to match our fixed function
        )

        return_code = run_process_with_realtime_output(process)
        captured = capfd.readouterr()

        assert return_code == 0
        # Verify unicode content was captured
        assert "Hello 🌍 World" in captured.out
        assert "Error with émojis 🚨" in captured.err
        # The binary data should also be present (displayed as escaped sequences)
        assert "Binary data:" in captured.out
        assert "Binary error:" in captured.err

    def test_immediate_exit_process(self, create_script, capfd):
        """Test processes that exit immediately without much output."""
        script_content = """
import sys
sys.exit(42)
    """
        script_path = create_script(script_content)

        process = subprocess.Popen(
            [sys.executable, script_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=False,
        )

        return_code = run_process_with_realtime_output(process)
        captured = capfd.readouterr()

        assert return_code == 42
        assert "Warning: process exited with non-zero return code: 42" in captured.err
        # Should complete quickly without any threading issues

    def test_warning_message_format_for_non_zero_exit(self, create_script, capfd):
        """Test that the warning message format matches what the existing test expects."""
        script_content = """
import sys
print("Process output")
sys.exit(42)
    """
        script_path = create_script(script_content)

        process = subprocess.Popen(
            [sys.executable, script_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=False,  # Use bytes mode to match fixed function
        )

        return_code = run_process_with_realtime_output(process)
        captured = capfd.readouterr()

        assert return_code == 42
        assert "Warning: process exited with non-zero return code: 42" in captured.err

    def test_file_descriptor_closure_during_cleanup(
        self,
    ):
        """Test that file descriptors are closed during forced cleanup."""
        mock_process = MagicMock()
        mock_process.wait.return_value = 0
        mock_process.poll.return_value = 0

        # Create mock file objects that track close() calls
        mock_stdout = MagicMock()
        mock_stderr = MagicMock()
        mock_process.stdout = mock_stdout
        mock_process.stderr = mock_stderr

        # This just tests that the function works with mocked file objects
        return_code = run_process_with_realtime_output(mock_process)
        assert return_code == 0

    def test_exception_handling_during_file_closure(
        self,
    ):
        """Test that exceptions during file closure are handled gracefully."""
        mock_process = MagicMock()
        mock_process.wait.return_value = 0
        mock_process.poll.return_value = 0

        # Mock file objects that raise exceptions when closed
        mock_stdout = MagicMock()
        mock_stderr = MagicMock()
        mock_stdout.close.side_effect = OSError("Already closed")
        mock_stderr.close.side_effect = OSError("Already closed")
        mock_process.stdout = mock_stdout
        mock_process.stderr = mock_stderr

        # Should not raise exception despite close() failures in finally block
        return_code = run_process_with_realtime_output(mock_process)
        assert return_code == 0

    def test_bytes_vs_text_mode_compatibility(self, create_script, capfd):
        """Test that function works with text=False subprocess (bytes mode)."""
        script_content = """
import sys
import os

# Write some bytes directly
sys.stdout.buffer.write(b"Bytes output\\n")
sys.stderr.buffer.write(b"Bytes error\\n")

# Write some text that gets encoded
sys.stdout.write("Text output\\n")
sys.stderr.write("Text error\\n")

sys.exit(0)
    """
        script_path = create_script(script_content)

        # Use text=False to ensure we get bytes from the subprocess
        process = subprocess.Popen(
            [sys.executable, script_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=False,  # This is what the fixed function expects
        )

        return_code = run_process_with_realtime_output(process)
        captured = capfd.readouterr()

        assert return_code == 0
        # Verify both byte and text output were captured
        assert "Bytes output" in captured.out
        assert "Text output" in captured.out
        assert "Bytes error" in captured.err
        assert "Text error" in captured.err

    def test_process_cleanup_in_finally_block(
        self,
    ):
        """Test that process cleanup happens even if an exception occurs."""
        mock_process = MagicMock()
        mock_process.poll.return_value = None  # Process still running
        mock_process.stdout = MagicMock()
        mock_process.stderr = MagicMock()

        # Make the main logic raise an exception
        mock_process.wait.side_effect = Exception("Simulated error")

        with pytest.raises(Exception, match="Simulated error"):
            run_process_with_realtime_output(mock_process)

        # Verify cleanup was attempted despite the exception
        mock_process.terminate.assert_called_once()


def test_normal_execution_stdout_stderr(create_script, capfd):
    """Test normal execution with output to both stdout and stderr.

    Note: This test works with capfd - not with capsys. This is to preserve ANSI and
    progress bar.
    """
    script_content = """
import sys
import time
print("Output to stdout")
print("Error output to stderr", file=sys.stderr)
time.sleep(0.1) # Give reader threads time to process
print("More stdout")
sys.exit(0)
"""
    script_path = create_script(script_content)

    process = subprocess.Popen(
        [sys.executable, script_path],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,  # Use text=True for easier assertion
        bufsize=1,
    )

    return_code = run_process_with_realtime_output(process)
    captured = capfd.readouterr()

    assert return_code == 0
    assert "Output to stdout" in captured.out
    assert "More stdout" in captured.out
    assert "Error output to stderr" in captured.err
    # Check that the warning for non-zero exit code is NOT printed
    assert "Warning: process exited with non-zero return code" not in captured.err


def test_non_zero_exit_code(create_script, capfd):
    """Test execution where the subprocess exits with a non-zero code."""
    script_content = """
import sys
print("Exiting with status 5", file=sys.stderr)
sys.exit(5)
"""
    script_path = create_script(script_content)

    process = subprocess.Popen(
        [sys.executable, script_path],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        bufsize=1,
    )

    return_code = run_process_with_realtime_output(process)
    captured = capfd.readouterr()  # Use capfd to capture stderr reliably

    assert return_code == 5
    assert "Exiting with status 5" in captured.err
    assert "Warning: process exited with non-zero return code: 5" in captured.err


def test_interruption_no_deadlock(create_script):
    """
    Test that terminating the process externally doesn't cause deadlock.
    We run run_process_with_realtime_output in a thread and terminate
    the subprocess from the main thread.
    """
    script_content = """
import time
import sys
print("Process started")
sys.stdout.flush()
try:
    time.sleep(10) # Sleep long enough to be interrupted
except KeyboardInterrupt:
    print("Process interrupted")
    sys.exit(1)
print("Process finished normally (should not happen in this test)")
sys.exit(0)
"""
    script_path = create_script(script_content)

    process = subprocess.Popen(
        [sys.executable, script_path],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        bufsize=1,
    )

    # Give the process a moment to start
    time.sleep(0.2)

    # Run the function under test in a separate thread
    thread_result = {}

    def target():
        thread_result["return_code"] = run_process_with_realtime_output(process)

    runner_thread = threading.Thread(target=target)
    runner_thread.start()

    # Wait a bit to ensure reader threads are likely running
    time.sleep(0.3)

    # Simulate an external interruption by terminating the subprocess
    print("\n>>> Terminating subprocess...")
    process.terminate()  # Sends SIGTERM

    # Wait for the runner thread to finish, with a timeout to detect deadlocks
    runner_thread.join(timeout=5.0)  # Generous timeout

    print(">>> Runner thread joined")

    # Check if the thread is still alive (indicates deadlock)
    if runner_thread.is_alive():
        # Try killing the process more forcefully if terminate didn't work
        # (This might happen on Windows sometimes)
        print(">>> Runner thread seems deadlocked, trying process.kill()")
        try:
            process.kill()
            runner_thread.join(timeout=2.0)  # Shorter timeout after kill
            if runner_thread.is_alive():
                pytest.fail(
                    "Deadlock detected: runner thread did not exit after process.kill()"
                )
        except Exception as e:
            pytest.fail(f"Deadlock detected and failed during kill: {e}")
        pytest.fail(
            "Deadlock detected: runner thread did not exit even after process.kill()"
        )

    # Check if the runner thread completed successfully
    assert "return_code" in thread_result, "Runner thread did not set return code"

    # The return code should reflect the termination signal
    # On POSIX, terminate is signal 15, exit code is 128 + signal = 143 or -15
    # On Windows, terminate usually results in exit code 1 (or sometimes other values)
    print(f">>> Subprocess final poll: {process.poll()}")
    print(
        f">>> run_process_with_realtime_output returned: {thread_result.get('return_code')}"
    )

    # Check that the process is actually terminated
    assert process.poll() is not None, "Subprocess was not terminated"

    # We check the return code *from the function*, not process.poll() directly,
    # as the function is supposed to return process.returncode

    # On Linux/macOS, SIGTERM (15) usually results in -15 or 143
    term_signal = -signal.SIGTERM
    expected_return_code = 128 + signal.SIGTERM
    assert (
        thread_result["return_code"] in (term_signal, expected_return_code)
    ), f"Expected return code {term_signal} or {expected_return_code} after SIGTERM, got {thread_result['return_code']}"

    # We don't check captured output here as it's timing-dependent due to the interruption
